[package]
name = "bigly-numbers"
version = "0.1.0"
authors = ["Paul Kukowski <kukowskipaul@gmail.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
rand = "0.9.0"
getrandom = { version = "0.3.1", features = ["wasm_js"] }
wasm-bindgen = "0.2"
